[package]
name = "graph_data_api"
version = "0.1.0"
authors = ["davidroeca <david.roeca@gmail.com>"]

[dependencies]
rocket = "0.2.6"
rocket_codegen = "0.2.6"
rocket_contrib = "0.2.6"
serde = "0.9.10"
serde_json = "0.9.10"
serde_derive = "0.9.10"
